Ajout présentation 'Introduction à R et au tidyverse'
spyrales/web pull request #15
Opened 2020-03-21 16:45 UTC by juba

À la demande de @RLesur, voici une proposition de billet pour le document "Introduction à R et au tidyverse". N'hésitez pas à y apporter toutes corrections utiles !

2020-03-21 17:00 UTC, RLesur commented
Mille mercis @juba !

2020-03-21 20:45 UTC, RLesur commented
@juba j'ai juste une petite question de curiosité. Est-ce qu'il t'est arrivé de dispenser cette formation avec RStudio Cloud ? En effet, je me demandais (voir #13) si RSC n'était pas une option très adaptée dans le contexte du confinement. J'aimerais bien ton avis sur ce sujet.  

Et pour aller au bout de mon idée, je me demandais si on ne pourrait pas créer un projet RStudio Cloud qui serait déjà opérationnel et adapté à ta formation  : on pourrait rajouter le lien dans ton post et comme ça les personnes intéressées pourraient démarrer en 1 clic.

2020-03-21 23:00 UTC, RLesur commented
J'ai fait un projet dans lequel j'ai installé le tidyverse et questionr. J'ai aussi changé `LANGUAGE` à `fr` pour que les messages soit en :fr: : https://rstudio.cloud/project/1056996

2020-03-22 11:27 UTC, juba commented
Je suis partagé sur l'idée de RSC : 

- d'un côté je trouve ça bien que les personnes installent elles-mêmes les outils, surtout quand ça n'est pas trop compliqué.
- d'un autre côté en formation je suis là pour aider s'il y a un problème, là ça pourrait être décourageant si quelque chose coince.

C'est la même chose pour les projets : je trouve ça bien que les personnes installent les packages et créent les projets elles-mêmes, mais dans une formation en présentiel c'est évidemment différent d'une situation d'autoformation.

Donc j'aurais peut-être tendance à dire : privilégier le fait de travailler en local si on est à l'aise un minimum et qu'on ne rencontre pas de problème, mais ça peut être bien d'avoir une solution RCS des secours si jamais ça coince ?

Merci en tous cas !

2020-03-22 12:49 UTC, RLesur commented
> privilégier le fait de travailler en local si on est à l'aise un minimum et qu'on ne rencontre pas de problème, mais ça peut être bien d'avoir une solution RCS des secours si jamais ça coince ?

Merci. Ca me semble être un bon compromis. En effet, je sais que l'installation de R, RStudio et de packages va être difficile pour plusieurs personnes. Certains collègues m'ont déjà signalé qu'ils ne possédaient qu'un vieil ordinateur qui n'avance pas (on n'est pas tous geeks) et je sais qu'ils ne sont pas trop à l'aise avec la matière informatique. J'aimerais qu'ils ne décrochent pas (surtout dans le contexte dans lequel nous sommes). 

Autres éléments de contexte lié à mon boulot : les personnes n'ont pas le droit d'installer de logiciels sur leurs postes de travail. Ils font du R exclusivement via RStudio Server. Et par ailleurs, nous leur demandons de **ne pas installer** de packages afin que tout le monde ait les mêmes versions (ils peuvent quand même le faire mais connaissent les conséquences potentielles). J'avoue avoir été plutôt séduit par RSC car je sais que mes collègues y trouveraient un environnement de travail extrêmement proche de celui qu'on leur met à disposition au boulot.

2020-03-22 14:21 UTC, juba commented
Oui, tu as tout à fait raison, j'ai tendance à trop garder en tête le contexte le plus courant pour moi de formation en présentiel. Du coup merci pour l'intiative RSC.

2020-03-22 14:54 UTC, RLesur commented
@juba Désolé de te déranger à nouveau mais le fait d'échanger sur ton introduction au tidyverse me rappelle une question que je me suis régulièrement posée : quelle est l'articulation entre les projets https://github.com/juba/tidyverse et https://github.com/larmarange/analyse-R ? Est-ce une collaboration ou bien un effet de la licence ouverte que tu as retenue pour l'introduction au tidyverse ?  
Là encore, c'est de la pure curiosité :smile:

2020-03-22 15:12 UTC, juba commented
Ça n'est pas directement une collaboration. Il y a déjà pas mal de temps, avant l'apparition du tidyverse, quand mon doc n'était qu'une introduction à R, Joseph m'avait demandé s'il pouvait réutiliser des parties pour son document à lui. Je lui avais évidemment donné mon accord.

Apparemment il a repris depuis certaines de mes parties sur le tidyverse. Mais les deux projets sont indépendant, ils évoluent en parallèle.

2020-03-23 18:24 UTC, larmarange commented
En effet, la première version d'analyse-R est parti d'un document développé par @juba (<https://github.com/juba/intro-r>) qu'il avait mis sous licence libre et qui a été complété depuis par d'autres éléments. De même, analyse-R a bénéficié de certains passages de la nouvelle introduction à R et au tidyverse de @juba.

Les deux projets ont des finalités un peu différentes (un document cohérent et plus restreint pour l'introduction à R et au tidyverse), des chapitres plus au moins autonomes, sans exercice et sur des sujets plus variés pour analyse-R.

Les deux projets profitent des avantages des licences libres qui permettent la réexploitation et la rediffusion des contenus.

2020-03-23 18:27 UTC, larmarange commented
Pour des personnes ne connaissant pas R ou le tidyverse, je dirais que l'introduction de @juba  est plus adaptée, analyse-R leur permettant, dans un second temps, de pouvoir approfondir des points non abordés dans cette introduction.

2020-03-23 20:47 UTC, RLesur approved these changes
Merci beaucoup @juba !

2020-03-23 20:47 UTC, RLesur commented on content/french/blog/20200321-introduction-r-tidyverse.md
> +date: 2020-03-21T17:17:10+01:00
Je change la date pour que le billet arrive après celui de présentation générale 

```suggestion
date: 2020-03-23T17:17:10+01:00
```

2020-03-24 00:11 UTC, RLesur commented
@juba Nous allons insérer des bio pour les auteurs de billet (cf. #21). Pourrais-tu nous en passer une, s'il-te-plait ?

2020-03-24 08:33 UTC, juba commented
Est-ce que ça ça irait ?

Ingénieur CNRS au Centre Max Weber à Lyon, je donne des formations d'introduction à R depuis une douzaine d'années, essentiellement auprès d'un public de chercheur.es et de doctorant.es. Je développe également plusieurs packages dont `questionr`, `explor`, `rmdformats` ou `rainette`.

2020-03-24 10:47 UTC, RLesur commented
@juba On va commencer par intégrer ça dans le site web, on regarde ce que ça rend et on revient vers toi le cas échéant pour rallonger la sauce.

2020-03-25 15:29 UTC, RLesur requested changes
Je change simplement la valeur de `draft` à `true` pour faciliter le merge et faire ensuite une revue du site en local avant publication.

2020-03-25 15:29 UTC, RLesur commented on content/french/blog/20200321-introduction-r-tidyverse.md
> +draft: false
Un bête détail pour que le merge de la PR soit plus simple :

```suggestion
draft: true
```

2020-03-25 15:30 UTC, RLesur approved these changes

2020-03-25 15:33 UTC, RLesur commented
FTR, [la bio de ](https://github.com/spyrales/web/pull/15#issuecomment-603101639)@juba a été intégrée par #24.

2020-03-25 15:35 UTC, merged