une présentation rapide d'analyse-R
spyrales/web pull request #20
Opened 2020-03-23 18:18 UTC by larmarange

à la demande de @RLesur une présentation succincte du site analyse-R

2020-03-23 20:32 UTC, RLesur commented
Un grand merci @larmarange ! Nous allons l'intégrer au plus vite !

2020-03-23 21:20 UTC, RLesur requested changes
Merci à nouveau @larmarange ! 
Je pense que ça devrait vraiment bien éclairer les personnes qui veulent commencer/approfondir R.

J'ai simplement croisé deux typos que je vais corriger.

close https://github.com/spyrales/organisation/issues/3

2020-03-23 21:20 UTC, RLesur commented on content/french/blog/20200323-blog-introduction-analyse-R.md
> +Les chapitres sont oragnisées en trois grandes parties :
```suggestion
Les chapitres sont organisés en trois grandes parties :
```

2020-03-23 21:20 UTC, RLesur commented on content/french/blog/20200323-blog-introduction-analyse-R.md
> +<http://larmarange.github.io/analyse-R/>
```suggestion
<https://larmarange.github.io/analyse-R/>
```

2020-03-23 21:21 UTC, RLesur approved these changes

2020-03-24 00:11 UTC, RLesur commented
@larmarange Nous allons insérer des bio pour les auteurs de billet (cf. #21). Pourrais-tu nous en passer une, s'il-te-plait ?

2020-03-24 09:11 UTC, larmarange commented
Joseph Larmarange est démographe de santé publique à l’IRD et rattaché au Ceped (UMR 196, Université de Pari, IRD, Inserm). Il a développé plusieurs packages R (`labelled`, `prevR`) et [contribué](https://www.rdocumentation.org/collaborators/name/Joseph%20Larmarange) à plusieurs autres (`questionr`, `lubridate`, `knitr`, `GGally`, ...).

2020-03-24 09:11 UTC, larmarange commented
Merci pour la correction des coquilles

2020-03-25 16:50 UTC, RLesur requested changes
modification purement technique : merger dans master en draft

2020-03-25 16:50 UTC, RLesur commented on content/french/blog/20200323-blog-introduction-analyse-R.md
> +draft: false
Modif technique : merger la PR dans `master` en mode `draft` avant publication

```suggestion
draft: true
```

2020-03-25 16:51 UTC, RLesur approved these changes

2020-03-25 16:54 UTC, merged