AutoML-Vision
spyrales/web pull request #87
Opened 2020-04-24 16:14 UTC by jmbernabotto

Un billet pour parler de ma première expérience avec Vision AutoML de GCP

2020-04-27 12:06 UTC, Welsh44 commented
Bonjour @jmbernabotto 

À moins d'avoir fait une boulette, en récupérant ton repo et en le naçant avec Hugo, je me suis rendu compte que le fichier de ton article n'avait pas d'extension `md`.

Après l'avoir renommé, hugo m'indique :
`20200424-AutoML-Vision.md:7:1": failed to unmarshal YAML: yaml: line 6: did not find expected node content`

A tout hasard...

2020-04-27 12:31 UTC, jmbernabotto commented
Bonjour.
Oui, en effet, j’avais oublié ! 
Rectifié.


> Le 27 avr. 2020 à 14:06, Fred GALLOIS <notifications@github.com> a écrit :
> 
> 
> Bonjour @jmbernabotto <https://github.com/jmbernabotto>
> À moins d'avoir fait une boulette, en récupérant ton repo et en le naçant avec Hugo, je me suis rendu compte que le fichier de ton article n'avait pas d'extension md.
> 
> Après l'avoir renommé, hugo m'indique :
> 20200424-AutoML-Vision.md:7:1": failed to unmarshal YAML: yaml: line 6: did not find expected node content
> 
> A tout hasard...
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/spyrales/web/pull/87#issuecomment-619942489>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AJDEUSO5F3XKBGJWTHAL26DROVYNXANCNFSM4MQHHVXA>.
>

2020-04-27 13:36 UTC, Welsh44 commented
Il reste l'erreur 
` 20200424-AutoML-Vision.md:7:1": failed to unmarshal YAML: yaml: line 6: did not find expected node content`
Personnellement je ne suis pas un pro de Hugo donc je ne vois pas ce qui cloche y compris par comparaison avec d'autres posts (ou alors je suis fatigué).

@strainel  ou @RLesur une idée ?

2020-04-27 14:00 UTC, jmbernabotto commented
j'avais quelques erreurs de md. à priori corrigées, mais y a encore un blème !!

2020-04-27 15:12 UTC, Welsh44 commented
J'ai proposé une PR (https://github.com/jmbernabotto/web/pull/1) sur ton repository.
En fait, dans le tableau des tags il y a une virgule de trop au début du tableau.

2020-04-27 15:15 UTC, jmbernabotto commented
> J'ai proposé une PR ([jmbernabotto#1](https://github.com/jmbernabotto/web/pull/1)) sur ton repository.
> En fait, dans le tableau des tags il y a une virgule de trop au début du tableau.

punaise je l'avais pas vu celle-là !! merci

2020-04-28 19:07 UTC, strainel requested changes

2020-04-28 19:07 UTC, strainel commented on content/french/blog/20200424-AutoML-Vision.md
> +J'ai donc exporter le fichier csv créé lors de l'étiquetage, que j'ai ouvert sous mon tableur préféré. Chaque ligne correspond à un tableau étiqueté. Il y a 11 colonnes séparées par des virgules :
```suggestion
J'ai donc exporté le fichier csv créé lors de l'étiquetage, que j'ai ouvert sous mon tableur préféré. Chaque ligne correspond à un tableau étiqueté. Il y a 11 colonnes séparées par des virgules :
```

2020-04-28 19:07 UTC, strainel commented on content/french/blog/20200424-AutoML-Vision.md
> +Une fois cette étiquetage terminé, j'ai voulu lancer l'entrainement. Mais, j'avais une erreur, il manquait des images dans le validation set des hommes. Je n'ai pas compris pourquoi la plateforem y é
```suggestion
Une fois cette étiquetage terminé, j'ai voulu lancer l'entrainement. Mais, j'avais une erreur, il manquait des images dans le _validation set_ des hommes. Je n'ai pas compris pourquoi la plateforme y était arrivée toute seule pour les femmes et pas pour les hommes ! Il faut, d'après les préconisations de la plateforme une distribution 80% pour le _train set_, 10% pour le _test set_, 10% pour le _validation set_. 
```

2020-04-28 19:07 UTC, strainel commented on content/french/blog/20200424-AutoML-Vision.md
> +J'ai importé ces portraits dans un bucket (qu'on avait appris à créer dans une formation précédente) et j'ai commencé l'étiquetage de chacun des portraits dans le module de Vision. C'est un peu long
```suggestion
J'ai importé ces portraits dans un bucket (qu'on avait appris à créer dans une formation précédente) et j'ai commencé l'étiquetage de chacun des portraits dans le module de Vision. C'est un peu long, car il faut dessiner pour chaque portrait un cadre autour des éléments qui caractérisent la féminité ou la masculinité du portrait, puis ensuite lui donner une des deux étiquettes (créées au préalable) femme ou homme. Il y a un seul tableau où il y a une femme et un homme, je l'ai également choisi ! 
```

2020-04-28 19:07 UTC, strainel commented on content/french/blog/20200424-AutoML-Vision.md
> +Aussi, j'ai choisi pour mon premier test Vision AutoML, 54 portraits. 32 de femmes et 22 d'hommes. Visiblement, Modigliani faisait plus de portraits de femmes que d'hommes !!
```suggestion
Aussi, j'ai choisi pour mon premier test Vision AutoML, 54 portraits : 32 de femmes et 22 d'hommes. Visiblement, Modigliani faisait plus de portraits de femmes que d'hommes !! 
```

2020-04-28 19:07 UTC, strainel commented on content/french/blog/20200424-AutoML-Vision.md
> +date: 2020-04-24T17:30:00+01:00
```suggestion
date: 2020-04-29T09:30:00+01:00
```

2020-04-28 20:06 UTC, RLesur approved these changes
Super article, très enthousiasmant ! Merci beaucoup !!!

2020-04-28 20:06 UTC, RLesur commented on content/french/blog/20200424-AutoML-Vision.md
> +Aussi, après la très instructive présentation d'Alexander Usoltsev (auv@google.com) (_comment ils arrivent à avoir des adresses pareilles avec le nombre d'employés chez Google reste pour moi un mystè
Je me demande si Alexander est d'accord pour qu'on publie son adresse mail.

2020-04-28 20:21 UTC, jmbernabotto commented
oh la la la la les fautes d'orthographes !!!!! pfffff...merci Stéphane ! 
Merci Romain.

2020-04-28 20:24 UTC, jmbernabotto commented on content/french/blog/20200424-AutoML-Vision.md
> +Aussi, après la très instructive présentation d'Alexander Usoltsev (auv@google.com) (_comment ils arrivent à avoir des adresses pareilles avec le nombre d'employés chez Google reste pour moi un mystè
Oui, c'est une bonne remarque ! On peut retirer au pire. Et retirer ce qu'il y a entre parenthèses avec.

2020-04-28 20:35 UTC, jmbernabotto commented on content/french/blog/20200424-AutoML-Vision.md
> +Une fois cette étiquetage terminé, j'ai voulu lancer l'entrainement. Mais, j'avais une erreur, il manquait des images dans le validation set des hommes. Je n'ai pas compris pourquoi la plateforem y é
Il y a encore une faute à "cette étiquetage" mais je j'arrive pas à avoir la nouvelle version du md et j'ai peur de faire des bétises !

2020-04-28 21:35 UTC, strainel approved these changes

2020-04-28 21:35 UTC, strainel commented on content/french/blog/20200424-AutoML-Vision.md
> +Une fois cette étiquetage terminé, j'ai voulu lancer l'entrainement. Mais, j'avais une erreur, il manquait des images dans le validation set des hommes. Je n'ai pas compris pourquoi la plateforem y é
```suggestion
Une fois cet étiquetage terminé, j'ai voulu lancer l'entrainement. Mais, j'avais une erreur, il manquait des images dans le validation set des hommes. Je n'ai pas compris pourquoi la plateforem y était arrivé toute seule pour les femmes et pas pour les hommes ! Il faut, d'après les préconisations de la plateforme une distribution 80% pour le train set, 10% pour le test set, 10% poue le validation set. 
```

2020-04-28 21:36 UTC, strainel commented on content/french/blog/20200424-AutoML-Vision.md
> +Une fois cette étiquetage terminé, j'ai voulu lancer l'entrainement. Mais, j'avais une erreur, il manquait des images dans le validation set des hommes. Je n'ai pas compris pourquoi la plateforem y é
je viens de faire un review supplémentaire pour prendre en compte celle-ci

2020-04-28 21:49 UTC, merged

2020-04-28 22:12 UTC, strainel commented
j'ai validé sans trop vérifier... les demandes de mises à jour n'ont pas été traitées. :/ 
j'ai ouvert une issue #89

2020-04-29 04:32 UTC, jmbernabotto commented
Comment j fais alors ? 
Je corrige tout et je renvoie ?